/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    IconEpApple: typeof import('~icons/ep/apple')['default']
    IconEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IconEpCircleCheck: typeof import('~icons/ep/circle-check')['default']
    IconEpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    IconEpCircleClose: typeof import('~icons/ep/circle-close')['default']
    IconEpCircleCloseFilled: typeof import('~icons/ep/circle-close-filled')['default']
    IconEpExpand: typeof import('~icons/ep/expand')['default']
    IconEpFold: typeof import('~icons/ep/fold')['default']
    IconEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IconEpList: typeof import('~icons/ep/list')['default']
    IconEpLock: typeof import('~icons/ep/lock')['default']
    IconEpSetting: typeof import('~icons/ep/setting')['default']
    IconEpUser: typeof import('~icons/ep/user')['default']
    IconPixelarticonsNotes: typeof import('~icons/pixelarticons/notes')['default']
    IconPixelarticonsNotesDelete: typeof import('~icons/pixelarticons/notes-delete')['default']
    IconPixelarticonsNotesMultiple: typeof import('~icons/pixelarticons/notes-multiple')['default']
    IconPixelarticonsNotesPlus: typeof import('~icons/pixelarticons/notes-plus')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
